files: .
repos:
  - repo: local
    hooks:
      - id: test
        name: run tests
        entry: pytest ./src/test  
        language: python
        types: [python]
        stages: [push]
        always_run: true
  - repo: local
    hooks:
      - id: format
        name: run formatting
        entry: black .
        language: python
        types: [python]
        stages: [push]
        always_run: true
          
